# Generated by Django 6.0.5 on 2026-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_remove_partner_logo_url_favicon_theme_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='custom_redirect_url',
            field=models.URLField(blank=True, help_text='When someone clicks your store logo, they will be redirected to this URL. Leave blank to redirect to the homepage.', max_length=500, verbose_name='Custom Logo Redirect URL'),
        ),
    ]
