# Generated by Django 6.0.5 on 2026-08-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_partner_custom_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='News ticker text. You can use emoji like 🚀 🎁 📦 📢')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
