# Generated by Django 6.0.5 on 2026-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_newsticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='search_placeholder',
            field=models.CharField(default='পণ্যের নাম, কোড, ক্যাটাগরি ও সাব-ক্যাটাগরি লিখে সার্চ করুন', help_text='Placeholder text for the search bar', max_length=300),
        ),
    ]
