# Generated by Django 6.0.5 on 2026-08-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_sitelogo_search_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsticker',
            name='type',
            field=models.CharField(choices=[('ticker', 'News Ticker'), ('search_placeholder', 'Search Placeholder')], default='ticker', max_length=30),
        ),
    ]
