# Generated by Django 6.0.5 on 2026-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_newsticker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='shop_banner',
            field=models.ImageField(blank=True, help_text='Banner image shown at top of Shop Grid page', null=True, upload_to='site_banners/'),
        ),
    ]
