# Generated by Django 6.0.5 on 2026-08-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_sitelogo_shop_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSidebarSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_sidebar_sliders/')),
                ('title', models.CharField(blank=True, help_text='Optional title overlay', max_length=200)),
                ('link_url', models.CharField(blank=True, help_text='Link when clicked', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Sidebar Slider',
                'verbose_name_plural': 'Shop Sidebar Sliders',
                'ordering': ['order'],
            },
        ),
    ]
