# Generated by Django 6.0.5 on 2026-08-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_shopsidebarslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_banners/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Banner',
                'verbose_name_plural': 'Shop Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopSidebarBottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_sidebar_bottom/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Sidebar Bottom Banner',
                'verbose_name_plural': 'Shop Sidebar Bottom Banners',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sitelogo',
            name='shop_banner',
        ),
    ]
