# Generated by Django 6.0.5 on 2026-08-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_shopbanner_shopsidebarbottombanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='domain_name',
            field=models.CharField(blank=True, help_text='Partner website domain (e.g. example.com)', max_length=200, verbose_name='Domain'),
        ),
    ]
