# Generated by Django 6.0.5 on 2026-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_rename_partner_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineproduct',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Pharmaceutical company name', max_length=300, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='pack_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pack / box price (total)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='pack_size',
            field=models.CharField(blank=True, help_text='e.g. 30s pack, 5s pack, 1s pack', max_length=200, verbose_name='Pack Size'),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit / piece price', max_digits=10),
        ),
    ]
