# Generated by Django 6.0.5 on 2026-08-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_discount_card_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='medicine_inventory_enabled',
            field=models.BooleanField(default=True, help_text='When ON, POS tracks stock and deducts inventory. When OFF, POS works without stock tracking.', verbose_name='Medicine Inventory Enabled'),
        ),
    ]
