# Generated by Django 6.0.5 on 2026-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_add_section_to_sidebar_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='color',
            field=models.CharField(choices=[('#25D366', 'WhatsApp Green'), ('#1877F2', 'Facebook Blue'), ('#FF0000', 'YouTube Red'), ('#E4405F', 'Instagram Pink'), ('#000000', 'X / Black'), ('#1DA1F2', 'Twitter Blue'), ('#0A66C2', 'LinkedIn Blue'), ('#0088CC', 'Telegram Blue'), ('#CB2027', 'Pinterest Red'), ('#010101', 'TikTok Black'), ('#28a745', 'Phone / Call Green'), ('#0ABF53', 'Generic Green'), ('#6f42c1', 'Generic Purple'), ('#3d73dd', 'Generic Blue')], default='#1877F2', help_text='Background color for the floating bar icon (hex).', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopsidebarbottombanner',
            name='section',
            field=models.CharField(blank=True, choices=[('', 'All Sections (default)'), ('home_all', 'Homepage — All Over Available Product'), ('home_partner', 'Homepage — All Partner Product'), ('home_hot', 'Homepage — All Partner Hot Products'), ('shop', 'Shop Page'), ('partner', 'Partner Store')], default='', help_text='Which section this banner appears in. Leave blank for all sections.', max_length=30),
        ),
        migrations.AlterField(
            model_name='shopsidebarslider',
            name='section',
            field=models.CharField(blank=True, choices=[('', 'All Sections (default)'), ('home_all', 'Homepage — All Over Available Product'), ('home_partner', 'Homepage — All Partner Product'), ('home_hot', 'Homepage — All Partner Hot Products'), ('shop', 'Shop Page'), ('partner', 'Partner Store')], default='', help_text='Which section this slider appears in. Leave blank for all sections.', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon_class',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook (f)'), ('fab fa-facebook', 'Facebook'), ('fab fa-square-facebook', 'Facebook Square'), ('fab fa-x-twitter', 'X / Twitter (bird)'), ('fab fa-twitter', 'Twitter (old bird)'), ('fab fa-instagram', 'Instagram'), ('fab fa-youtube', 'YouTube'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-linkedin-in', 'LinkedIn'), ('fab fa-telegram', 'Telegram'), ('fab fa-pinterest-p', 'Pinterest'), ('fab fa-tiktok', 'TikTok'), ('fab fa-threads', 'Threads'), ('fab fa-snapchat', 'Snapchat'), ('fa fa-phone', 'Phone / Call'), ('fa fa-envelope', 'Email')], default='fab fa-facebook-f', help_text="Font Awesome icon class (brand icons start with 'fab', solid icons with 'fa')", max_length=100),
        ),
    ]
