# Generated by Django 6.0.5 on 2026-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_socialmedialink_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='footer_about',
            field=models.TextField(blank=True, default='', help_text='Short about text shown under the footer logo'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Copyright © 2025-2026 Uddoktar Dokan. All Rights Reserved.', help_text='Copyright line shown at the bottom of the footer', max_length=300),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='newsletter_subtitle',
            field=models.CharField(blank=True, default='Get the latest deals and special offers', help_text='Newsletter section subtitle', max_length=250),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='newsletter_title',
            field=models.CharField(blank=True, default='Sign up for newsletter', help_text='Newsletter section title', max_length=150),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_address_bd',
            field=models.CharField(blank=True, default='144/G,Zigatola(Near BGB Pilkhana)Mirpur-1,Dhaka:1206', help_text='Local (Bangladesh) address shown in the footer', max_length=300),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_address_us',
            field=models.CharField(blank=True, default='Delwar,USA', help_text='Foreign address shown in the footer (optional)', max_length=300),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_email',
            field=models.EmailField(blank=True, default='', help_text='Contact email shown in the footer (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_phone',
            field=models.CharField(blank=True, default='01910422200', help_text='Contact number shown in the footer', max_length=30),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='site_whatsapp',
            field=models.CharField(blank=True, default='8801910422200', help_text='WhatsApp number (country code + number, no +) used in the floating bar & footer', max_length=30),
        ),
    ]
