# Generated by Django 6.0.5 on 2026-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_sitelogo_footer_about_sitelogo_footer_copyright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload a payment card/brand logo', null=True, upload_to='payment_icons/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Or enter an external image URL (e.g. CDN) — used when no image is uploaded', max_length=500)),
                ('link', models.URLField(blank=True, default='', max_length=500, verbose_name='Link (optional)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Show this icon in the footer')),
            ],
            options={
                'verbose_name': 'Payment Icon',
                'verbose_name_plural': 'Payment Icons',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='show_contact_section',
            field=models.BooleanField(default=True, verbose_name='Show contact info column'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='show_copyright_bar',
            field=models.BooleanField(default=True, verbose_name='Show copyright bottom bar'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='show_follow_us_section',
            field=models.BooleanField(default=True, verbose_name='Show follow-us (social) column'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='show_newsletter_section',
            field=models.BooleanField(default=True, verbose_name='Show newsletter section'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='show_payment_icons',
            field=models.BooleanField(default=True, verbose_name='Show payment card icons'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='show_policy_buttons',
            field=models.BooleanField(default=True, verbose_name='Show policy buttons (Terms, Return & Refund, Company Policy)'),
        ),
    ]
