# Generated by Django 6.0.5 on 2026-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_paymenticon_sitelogo_show_contact_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay_time', models.PositiveIntegerField(default=3, help_text='Seconds each slide stays on screen (slider time)')),
                ('height', models.PositiveIntegerField(default=200, help_text='Slider height in pixels')),
                ('width', models.PositiveIntegerField(default=0, help_text='Slider width in pixels. Leave 0 for full width (100%).')),
                ('show_title', models.BooleanField(default=True, help_text='Show the title overlay on each slide')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Slider Settings',
                'verbose_name_plural': 'Shop Slider Settings',
            },
        ),
    ]
