# Generated by Django 6.0.5 on 2026-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_shopslidersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand name')),
                ('image', models.ImageField(upload_to='brands/', verbose_name='Brand logo image')),
                ('link', models.CharField(blank=True, help_text='e.g. /shop_grid/ or a full URL', max_length=300, verbose_name='Link (optional)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brand Logo',
                'verbose_name_plural': 'Brand Logos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_b2b_b2c_buttons', models.BooleanField(default=True, verbose_name='Show B2B / B2C buttons')),
                ('b2b_icon', models.CharField(default='fas fa-building', max_length=60, verbose_name='B2B icon (Font Awesome class)')),
                ('b2b_button_text', models.CharField(default='B2B Product', max_length=60, verbose_name='B2B button text')),
                ('b2b_url', models.CharField(blank=True, default='/shop_grid/', help_text='e.g. /shop_grid/ or a full URL', max_length=300, verbose_name='B2B button link')),
                ('b2c_icon', models.CharField(default='fas fa-shopping-cart', max_length=60, verbose_name='B2C icon (Font Awesome class)')),
                ('b2c_button_text', models.CharField(default='B2C Product', max_length=60, verbose_name='B2C button text')),
                ('b2c_url', models.CharField(blank=True, default='/shop_grid/', help_text='e.g. /shop_grid/ or a full URL', max_length=300, verbose_name='B2C button link')),
                ('show_tabbed_products', models.BooleanField(default=True, verbose_name='Show "All Over Available Product" section')),
                ('products_heading', models.CharField(default='All Over Available Product', max_length=200, verbose_name='Section heading')),
                ('tab_all_label', models.CharField(default='All', max_length=40, verbose_name='"All" tab label')),
                ('tab_new_label', models.CharField(default='New', max_length=40, verbose_name='"New" tab label')),
                ('tab_discounted_label', models.CharField(default='Discounted', max_length=40, verbose_name='"Discounted" tab label')),
                ('tab_hot_label', models.CharField(default='Hot Item', max_length=40, verbose_name='"Hot" tab label')),
                ('show_random_product', models.BooleanField(default=True, verbose_name='Show "Random Product List" sidebars')),
                ('random_list_heading', models.CharField(default='Random Product List', max_length=200, verbose_name='Sidebar heading')),
                ('show_partner_products', models.BooleanField(default=True, verbose_name='Show "All Partner Product" section')),
                ('partner_products_heading', models.CharField(default='All Partner Product', max_length=200, verbose_name='Section heading')),
                ('show_partner_hot_products', models.BooleanField(default=True, verbose_name='Show "All Partner Hot Products" section')),
                ('partner_hot_products_heading', models.CharField(default='All Partner Hot Products', max_length=200, verbose_name='Section heading')),
                ('show_blog_marquee', models.BooleanField(default=True, verbose_name='Show "New Arrival Product" blog marquee')),
                ('new_arrival_heading', models.CharField(default='New Arrival Product', max_length=200, verbose_name='Blog marquee heading')),
                ('show_videos', models.BooleanField(default=True, verbose_name='Show "Our Videos" section')),
                ('videos_heading', models.CharField(default='Our Videos', max_length=200, verbose_name='Video section heading')),
                ('home_video_embed', models.CharField(blank=True, default='https://www.youtube.com/embed/q73R90FJZdQ?rel=0', help_text='Embed URL from "Share -> Embed" (https://www.youtube.com/embed/...)', max_length=500, verbose_name='YouTube video embed URL')),
                ('show_promo_cards', models.BooleanField(default=True, verbose_name='Show promo cards (Buy 2 items, Daily Sales, ...)')),
                ('show_brand_marquee', models.BooleanField(default=True, verbose_name='Show "Our Partner Brands" marquee')),
                ('brands_heading', models.CharField(default='Our Partner Brands', max_length=200, verbose_name='Brands marquee heading')),
                ('show_home_banner', models.BooleanField(default=False, help_text='Render the "Home Banner" images as a full-width strip above the promo cards. Manage images under Home Banner.', verbose_name='Show home banner strip')),
                ('shop_heading', models.CharField(default='ALL PRODUCTS', max_length=200, verbose_name='Shop page title')),
                ('show_shop_labels', models.BooleanField(default=True, verbose_name='Show the Labels filter list (All / New / Hot / Discounted)')),
                ('shop_label_all', models.CharField(default='All', max_length=40, verbose_name='Labels list "All" caption')),
                ('shop_label_new', models.CharField(default='New', max_length=40, verbose_name='Labels list "New" caption')),
                ('shop_label_hot', models.CharField(default='Hot', max_length=40, verbose_name='Labels list "Hot" caption')),
                ('shop_label_discounted', models.CharField(default='Discounted', max_length=40, verbose_name='Labels list "Discounted" caption')),
                ('show_share_buttons', models.BooleanField(default=True, verbose_name='Show social share buttons on product page')),
                ('shipping_delivery_title', models.CharField(default='Delivery', max_length=100, verbose_name='Delivery card title')),
                ('shipping_delivery_text', models.CharField(default='Nationwide delivery across Bangladesh. Delivered within 3-7 business days.', max_length=300, verbose_name='Delivery card text')),
                ('shipping_return_title', models.CharField(default='Return Policy', max_length=100, verbose_name='Return card title')),
                ('shipping_return_text', models.CharField(default='Return within 7 days for a full refund or exchange. Unused, original packaging.', max_length=300, verbose_name='Return card text')),
                ('shipping_payment_title', models.CharField(default='Payment', max_length=100, verbose_name='Payment card title')),
                ('shipping_payment_text', models.CharField(default='Cash on Delivery (COD) available for all orders within Bangladesh.', max_length=300, verbose_name='Payment card text')),
                ('contact_heading', models.CharField(default='Contact Us', max_length=200, verbose_name='Contact page title')),
                ('discount_heading', models.CharField(default='Discount Card', max_length=200, verbose_name='Discount Card page title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage & Page Settings',
                'verbose_name_plural': 'Homepage & Page Settings',
            },
        ),
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Card title')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Card subtitle')),
                ('icon', models.CharField(default='fa fa-gift', max_length=60, verbose_name='Icon (Font Awesome class)')),
                ('link', models.CharField(blank=True, help_text='e.g. /shop_grid/ or a full URL', max_length=300, verbose_name='Link (optional)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promo Card',
                'verbose_name_plural': 'Promo Cards',
                'ordering': ['order'],
            },
        ),
    ]
