# Generated by Django 6.0.5 on 2026-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_homepage_settings_promo_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='show_desktop',
            field=models.BooleanField(default=True, verbose_name='Show in desktop menu'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='show_mobile',
            field=models.BooleanField(default=True, verbose_name='Show in mobile menu'),
        ),
    ]
