# Generated by Django 6.0.5 on 2026-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='kind',
            field=models.CharField(choices=[('link', 'Link'), ('categories', 'Categories menu'), ('account', 'Login / Signup / Dashboard')], default='link', help_text="'Categories menu' renders the categories button + mega menu. 'Login / Signup / Dashboard' renders the account button (login/signup when logged out, dashboard when logged in).", max_length=20),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='open_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='url',
            field=models.CharField(blank=True, help_text="Named URL (e.g. 'home', 'shop_grid') or path (e.g. '/shop/'). Not used for Categories / Account buttons.", max_length=200),
        ),
    ]
