# Generated by Django 6.0.5 on 2026-09-12 22:21

from django.db import migrations, models


def seed_slider_configs(apps, schema_editor):
    ShopSliderConfig = apps.get_model('store', 'ShopSliderConfig')
    rows = [
        ('banner', 3, 200, 0, True),
        ('sidebar', 3, 250, 0, True),
        ('sidebar_bottom', 3, 250, 0, True),
    ]
    for area, time, height, width, active in rows:
        ShopSliderConfig.objects.get_or_create(
            area=area,
            defaults=dict(autoplay_time=time, height=height, width=width, show_title=True, is_active=active),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_seed_nav_menu_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSliderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('banner', 'Top Banner (Shop page)'), ('sidebar', 'Sidebar Slider (Shop page)'), ('sidebar_bottom', 'Sidebar Bottom Banner (Shop page)')], max_length=30, unique=True)),
                ('autoplay_time', models.PositiveIntegerField(default=3, help_text='Seconds each slide stays on screen (slide changing time)')),
                ('height', models.PositiveIntegerField(default=250, help_text='Slider container height in pixels')),
                ('width', models.PositiveIntegerField(default=0, help_text='Slider container width in pixels. Leave 0 for full width (100%).')),
                ('show_title', models.BooleanField(default=True, help_text='Show the title overlay on each slide')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slider on the page')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Slider Setting',
                'verbose_name_plural': 'Shop Slider Settings',
            },
        ),
        migrations.DeleteModel(
            name='ShopSliderSettings',
        ),
        migrations.RunPython(seed_slider_configs, migrations.RunPython.noop),
    ]
