"""
Bangladesh administrative geography: divisions, districts, upazilas
with English/Bengali names and lookup helpers.
"""

DIVISIONS_BN = {
    'Barisal Division': 'বরিশাল বিভাগ',
    'Chittagong Division': 'চট্টগ্রাম বিভাগ',
    'Dhaka Division': 'ঢাকা বিভাগ',
    'Khulna Division': 'খুলনা বিভাগ',
    'Mymensingh Division': 'ময়মনসিংহ বিভাগ',
    'Rajshahi Division': 'রাজশাহী বিভাগ',
    'Rangpur Division': 'রংপুর বিভাগ',
    'Sylhet Division': 'সিলেট বিভাগ',
}

DIVISION_LOOKUP = {
    'Barisal': 'Barisal Division',
    'Chittagong': 'Chittagong Division',
    'Dhaka': 'Dhaka Division',
    'Khulna': 'Khulna Division',
    'Mymensingh': 'Mymensingh Division',
    'Rajshahi': 'Rajshahi Division',
    'Rangpur': 'Rangpur Division',
    'Sylhet': 'Sylhet Division',
}

DISTRICTS = {
    'Bagerhat District': {'bn': 'বাগেরহাট জেলা', 'division': 'Khulna Division'},
    'Bandarban District': {'bn': 'বান্দরবান জেলা', 'division': 'Chittagong Division'},
    'Barguna District': {'bn': 'বরগুনা জেলা', 'division': 'Barisal Division'},
    'Barisal District': {'bn': 'বরিশাল জেলা', 'division': 'Barisal Division'},
    'Bhola District': {'bn': 'ভোলা জেলা', 'division': 'Barisal Division'},
    'Bogra District': {'bn': 'বগুড়া জেলা', 'division': 'Rajshahi Division'},
    'Brahmanbaria District': {'bn': 'ব্রাহ্মণবাড়িয়া জেলা', 'division': 'Chittagong Division'},
    'Chandpur District': {'bn': 'চাঁদপুর জেলা', 'division': 'Chittagong Division'},
    'Chapainawabganj District': {'bn': 'চাঁপাইনবাবগঞ্জ জেলা', 'division': 'Rajshahi Division'},
    'Chittagong District': {'bn': 'চট্টগ্রাম জেলা', 'division': 'Chittagong Division'},
    'Chuadanga District': {'bn': 'চুয়াডাঙ্গা জেলা', 'division': 'Khulna Division'},
    'Comilla District': {'bn': 'কুমিল্লা জেলা', 'division': 'Chittagong Division'},
    "Cox's Bazar District": {'bn': 'কক্সবাজার জেলা', 'division': 'Chittagong Division'},
    'Dhaka District': {'bn': 'ঢাকা জেলা', 'division': 'Dhaka Division'},
    'Dinajpur District': {'bn': 'দিনাজপুর জেলা', 'division': 'Rangpur Division'},
    'Faridpur District': {'bn': 'ফরিদপুর জেলা', 'division': 'Dhaka Division'},
    'Feni District': {'bn': 'ফেনী জেলা', 'division': 'Chittagong Division'},
    'Gaibandha District': {'bn': 'গাইবান্ধা জেলা', 'division': 'Rangpur Division'},
    'Gazipur District': {'bn': 'গাজীপুর জেলা', 'division': 'Dhaka Division'},
    'Gopalganj District': {'bn': 'গোপালগঞ্জ জেলা', 'division': 'Dhaka Division'},
    'Habiganj District': {'bn': 'হবিগঞ্জ জেলা', 'division': 'Sylhet Division'},
    'Jamalpur District': {'bn': 'জামালপুর জেলা', 'division': 'Mymensingh Division'},
    'Jessore District': {'bn': 'যশোর জেলা', 'division': 'Khulna Division'},
    'Jhalokati District': {'bn': 'ঝালকাঠি জেলা', 'division': 'Barisal Division'},
    'Jhenaidah District': {'bn': 'ঝিনাইদহ জেলা', 'division': 'Khulna Division'},
    'Joypurhat District': {'bn': 'জয়পুরহাট জেলা', 'division': 'Rajshahi Division'},
    'Khagrachhari District': {'bn': 'খাগড়াছড়ি জেলা', 'division': 'Chittagong Division'},
    'Khulna District': {'bn': 'খুলনা জেলা', 'division': 'Khulna Division'},
    'Kishoreganj District': {'bn': 'কিশোরগঞ্জ জেলা', 'division': 'Dhaka Division'},
    'Kurigram District': {'bn': 'কুড়িগ্রাম জেলা', 'division': 'Rangpur Division'},
    'Kushtia District': {'bn': 'কুষ্টিয়া জেলা', 'division': 'Khulna Division'},
    'Lakshmipur District': {'bn': 'লক্ষ্মীপুর জেলা', 'division': 'Chittagong Division'},
    'Lalmonirhat District': {'bn': 'লালমনিরহাট জেলা', 'division': 'Rangpur Division'},
    'Madaripur District': {'bn': 'মাদারীপুর জেলা', 'division': 'Dhaka Division'},
    'Magura District': {'bn': 'মাগুরা জেলা', 'division': 'Khulna Division'},
    'Manikganj District': {'bn': 'মানিকগঞ্জ জেলা', 'division': 'Dhaka Division'},
    'Meherpur District': {'bn': 'মেহেরপুর জেলা', 'division': 'Khulna Division'},
    'Moulvibazar District': {'bn': 'মৌলভীবাজার জেলা', 'division': 'Sylhet Division'},
    'Munshiganj District': {'bn': 'মুন্সিগঞ্জ জেলা', 'division': 'Dhaka Division'},
    'Mymensingh District': {'bn': 'ময়মনসিংহ জেলা', 'division': 'Mymensingh Division'},
    'Naogaon District': {'bn': 'নওগাঁ জেলা', 'division': 'Rajshahi Division'},
    'Narail District': {'bn': 'নড়াইল জেলা', 'division': 'Khulna Division'},
    'Narayanganj District': {'bn': 'নারায়ণগঞ্জ জেলা', 'division': 'Dhaka Division'},
    'Narsingdi District': {'bn': 'নরসিংদী জেলা', 'division': 'Dhaka Division'},
    'Natore District': {'bn': 'নাটোর জেলা', 'division': 'Rajshahi Division'},
    'Netrakona District': {'bn': 'নেত্রকোনা জেলা', 'division': 'Mymensingh Division'},
    'Nilphamari District': {'bn': 'নীলফামারী জেলা', 'division': 'Rangpur Division'},
    'Noakhali District': {'bn': 'নোয়াখালী জেলা', 'division': 'Chittagong Division'},
    'Pabna District': {'bn': 'পাবনা জেলা', 'division': 'Rajshahi Division'},
    'Panchagarh District': {'bn': 'পঞ্চগড় জেলা', 'division': 'Rangpur Division'},
    'Patuakhali District': {'bn': 'পটুয়াখালী জেলা', 'division': 'Barisal Division'},
    'Pirojpur District': {'bn': 'পিরোজপুর জেলা', 'division': 'Barisal Division'},
    'Rajbari District': {'bn': 'রাজবাড়ী জেলা', 'division': 'Dhaka Division'},
    'Rajshahi District': {'bn': 'রাজশাহী জেলা', 'division': 'Rajshahi Division'},
    'Rangamati Hill District': {'bn': 'রাঙ্গামাটি জেলা', 'division': 'Chittagong Division'},
    'Rangpur District': {'bn': 'রংপুর জেলা', 'division': 'Rangpur Division'},
    'Satkhira District': {'bn': 'সাতক্ষীরা জেলা', 'division': 'Khulna Division'},
    'Shariatpur District': {'bn': 'শরীয়তপুর জেলা', 'division': 'Dhaka Division'},
    'Sherpur District': {'bn': 'শেরপুর জেলা', 'division': 'Mymensingh Division'},
    'Sirajganj District': {'bn': 'সিরাজগঞ্জ জেলা', 'division': 'Rajshahi Division'},
    'Sunamganj District': {'bn': 'সুনামগঞ্জ জেলা', 'division': 'Sylhet Division'},
    'Sylhet District': {'bn': 'সিলেট জেলা', 'division': 'Sylhet Division'},
    'Tangail District': {'bn': 'টাঙ্গাইল জেলা', 'division': 'Dhaka Division'},
    'Thakurgaon District': {'bn': 'ঠাকুরগাঁও জেলা', 'division': 'Rangpur Division'},
}

UPAZILAS = {
    'Abhaynagar': {'bn': 'অভয়নগর', 'district': 'Jessore District'},
    'Adamdighi': {'bn': 'আদমদিঘী', 'district': 'Bogra District'},
    'Adarsh Sadar': {'bn': '', 'district': 'Comilla District'},
    'Aditmari': {'bn': 'আদিতমারী', 'district': 'Lalmonirhat District'},
    'Agailjhara': {'bn': 'আগৈলঝাড়া', 'district': 'Barisal District'},
    'Ajmiriganj': {'bn': 'আজমিরীগঞ্জ', 'district': 'Habiganj District'},
    'Akhaura': {'bn': 'আখাউড়া', 'district': 'Brahmanbaria District'},
    'Akkelpur': {'bn': 'আক্কেলপুর', 'district': 'Joypurhat District'},
    'Alamdanga': {'bn': 'আলমডাঙ্গা', 'district': 'Chuadanga District'},
    'Alfadanga': {'bn': 'আলফাডাঙ্গা', 'district': 'Faridpur District'},
    'Alikadam': {'bn': 'আলীকদম', 'district': 'Bandarban District'},
    'Amtali': {'bn': 'আমতলী', 'district': 'Barguna District'},
    'Anwara': {'bn': 'আনোয়ারা', 'district': 'Chittagong District'},
    'Araihazar': {'bn': 'আড়াইহাজার', 'district': 'Narayanganj District'},
    'Asashuni': {'bn': 'আশাশুনি', 'district': 'Satkhira District'},
    'Ashuganj': {'bn': 'আশুগঞ্জ', 'district': 'Brahmanbaria District'},
    'Ashtagram': {'bn': 'অষ্টগ্রাম', 'district': 'Kishoreganj District'},
    'Atgharia': {'bn': 'আটঘরিয়া', 'district': 'Pabna District'},
    'Atpara': {'bn': 'আটপাড়া', 'district': 'Netrakona District'},
    'Atrai': {'bn': 'আত্রাই', 'district': 'Naogaon District'},
    'Atwari': {'bn': 'আটোয়ারী', 'district': 'Panchagarh District'},
    'Babuganj': {'bn': 'বাবুগঞ্জ', 'district': 'Barisal District'},
    'Badalgachhi': {'bn': 'বদলগাছী', 'district': 'Naogaon District'},
    'Badarganj': {'bn': 'বদরগঞ্জ', 'district': 'Rangpur District'},
    'Bagha': {'bn': 'বাঘা', 'district': 'Rajshahi District'},
    'Baghaichhari': {'bn': 'বাঘাইছড়ি', 'district': 'Rangamati Hill District'},
    'Bagharpara': {'bn': 'বাঘারপাড়া', 'district': 'Jessore District'},
    'Bagatipara': {'bn': 'বাগাতিপাড়া', 'district': 'Natore District'},
    'Bagerhat Sadar': {'bn': 'বাগেরহাট সদর', 'district': 'Bagerhat District'},
    'Bagmara': {'bn': 'বাগমারা', 'district': 'Rajshahi District'},
    'Bahubal': {'bn': 'বাহুবল', 'district': 'Habiganj District'},
    'Bajitpur': {'bn': 'বাজিতপুর', 'district': 'Kishoreganj District'},
    'Bakerganj': {'bn': 'বাকেরগঞ্জ', 'district': 'Barisal District'},
    'Bakshiganj': {'bn': 'বকশীগঞ্জ', 'district': 'Jamalpur District'},
    'Balaganj': {'bn': 'বালাগঞ্জ', 'district': 'Sylhet District'},
    'Baliadangi': {'bn': 'বালিয়াডাঙ্গী', 'district': 'Thakurgaon District'},
    'Baliakandi': {'bn': 'বালিয়াকান্দি', 'district': 'Rajbari District'},
    'Bamna': {'bn': 'বামনা', 'district': 'Barguna District'},
    'Banaripara': {'bn': 'বানারীপাড়া', 'district': 'Barisal District'},
    'Bancharampur': {'bn': 'বাঞ্ছারামপুর', 'district': 'Brahmanbaria District'},
    'Bandarban Sadar': {'bn': 'বান্দরবান সদর', 'district': 'Bandarban District'},
    'Bandar': {'bn': 'বন্দর', 'district': 'Narayanganj District'},
    'Baniachong': {'bn': 'বানিয়াচং', 'district': 'Habiganj District'},
    'Banshkhali': {'bn': 'বাঁশখালী', 'district': 'Chittagong District'},
    'Baraigram': {'bn': 'বড়াইগ্রাম', 'district': 'Natore District'},
    'Baralekha': {'bn': 'বড়লেখা', 'district': 'Moulvibazar District'},
    'Barguna Sadar': {'bn': 'বরগুনা সদর', 'district': 'Barguna District'},
    'Barhatta': {'bn': 'বারহাট্টা', 'district': 'Netrakona District'},
    'Barisal Sadar': {'bn': 'বরিশাল সদর', 'district': 'Barisal District'},
    'Barkal': {'bn': 'বরকল', 'district': 'Rangamati Hill District'},
    'Barura': {'bn': 'বরুড়া', 'district': 'Comilla District'},
    'Basail': {'bn': 'বাসাইল', 'district': 'Tangail District'},
    'Batiaghata': {'bn': 'বটিয়াঘাটা', 'district': 'Khulna District'},
    'Bauphal': {'bn': 'বাউফল', 'district': 'Patuakhali District'},
    'Beanibazar': {'bn': 'বিয়ানীবাজার', 'district': 'Sylhet District'},
    'Begumganj': {'bn': 'বেগমগঞ্জ', 'district': 'Noakhali District'},
    'Belabo': {'bn': 'বেলাবো', 'district': 'Narsingdi District'},
    'Belkuchi': {'bn': 'বেলকুচি', 'district': 'Sirajganj District'},
    'Bera': {'bn': 'বেড়া', 'district': 'Pabna District'},
    'Betagi': {'bn': 'বেতাগী', 'district': 'Barguna District'},
    'Bhairab': {'bn': 'ভৈরব', 'district': 'Kishoreganj District'},
    'Bhaluka': {'bn': 'ভালুকা', 'district': 'Mymensingh District'},
    'Bhandaria': {'bn': 'ভাণ্ডারিয়া', 'district': 'Pirojpur District'},
    'Bhanga': {'bn': 'ভাঙ্গা', 'district': 'Faridpur District'},
    'Bhangura': {'bn': 'ভাঙ্গুড়া', 'district': 'Pabna District'},
    'Bhedarganj': {'bn': 'ভেড়ারগঞ্জ', 'district': 'Shariatpur District'},
    'Bheramara': {'bn': 'ভেড়ামারা', 'district': 'Kushtia District'},
    'Bholahat': {'bn': 'ভোলাহাট', 'district': 'Chapainawabganj District'},
    'Bhola Sadar': {'bn': 'ভোলা সদর', 'district': 'Bhola District'},
    'Bhuiyanpur': {'bn': 'ভূঞাপুর', 'district': 'Tangail District'},
    'Bhurungamari': {'bn': 'ভুরুঙ্গামারী', 'district': 'Kurigram District'},
    'Bijoynagar': {'bn': 'বিজয়নগর', 'district': 'Brahmanbaria District'},
    'Bilaichhari': {'bn': 'বিলাইছড়ি', 'district': 'Rangamati Hill District'},
    'Birampur': {'bn': 'বিরামপুর', 'district': 'Dinajpur District'},
    'Birganj': {'bn': 'বীরগঞ্জ', 'district': 'Dinajpur District'},
    'Biral': {'bn': 'বিরল', 'district': 'Dinajpur District'},
    'Bishwambharpur': {'bn': 'বিশ্বম্ভরপুর', 'district': 'Sunamganj District'},
    'Bishwanath': {'bn': 'বিশ্বনাথ', 'district': 'Sylhet District'},
    'Boalmari': {'bn': 'বোয়ালমারী', 'district': 'Faridpur District'},
    'Boalkhali': {'bn': 'বোয়ালখালী', 'district': 'Chittagong District'},
    'Bochaganj': {'bn': 'বোচাগঞ্জ', 'district': 'Dinajpur District'},
    'Boda': {'bn': 'বোদা', 'district': 'Panchagarh District'},
    'Bogra Sadar': {'bn': 'বগুড়া সদর', 'district': 'Bogra District'},
    'Borhanuddin': {'bn': 'বোরহানউদ্দিন', 'district': 'Bhola District'},
    'Brahmanbaria Sadar': {'bn': 'ব্রাহ্মণবাড়িয়া সদর', 'district': 'Brahmanbaria District'},
    'Brahmanpara': {'bn': 'ব্রাহ্মণপাড়া', 'district': 'Comilla District'},
    'Burichang': {'bn': 'বুড়িচং', 'district': 'Comilla District'},
    'Chagalnaiya': {'bn': 'ছাগলনাইয়া', 'district': 'Feni District'},
    'Chakaria': {'bn': 'চকরিয়া', 'district': "Cox's Bazar District"},
    'Chandanaish': {'bn': 'চন্দনাইশ', 'district': 'Chittagong District'},
    'Chandina': {'bn': 'চান্দিনা', 'district': 'Comilla District'},
    'Chandpur Sadar': {'bn': 'চাঁদপুর সদর', 'district': 'Chandpur District'},
    'Chapainawabganj Sadar': {'bn': 'চাঁপাইনবাবগঞ্জ সদর', 'district': 'Chapainawabganj District'},
    'Char Fashion': {'bn': 'চর ফ্যাশন', 'district': 'Bhola District'},
    'Char Rajibpur': {'bn': 'চর রাজিবপুর', 'district': 'Kurigram District'},
    'Charbhadrasan': {'bn': 'চরভদ্রাসন', 'district': 'Faridpur District'},
    'Charghat': {'bn': 'চারঘাট', 'district': 'Rajshahi District'},
    'Chatkhil': {'bn': 'চাটখিল', 'district': 'Noakhali District'},
    'Chatmohar': {'bn': 'চাটমোহর', 'district': 'Pabna District'},
    'Chauddagram': {'bn': 'চৌদ্দগ্রাম', 'district': 'Comilla District'},
    'Chaugachha': {'bn': 'চৌগাছা', 'district': 'Jessore District'},
    'Chauhali': {'bn': 'চৌহালি', 'district': 'Sirajganj District'},
    'Chhatak': {'bn': 'ছাতক', 'district': 'Sunamganj District'},
    'Chhagalnaiya': {'bn': 'ছাগলনাইয়া', 'district': 'Feni District'},
    'Chilmari': {'bn': 'চিলমারী', 'district': 'Kurigram District'},
    'Chirirbandar': {'bn': 'চিরিরবন্দর', 'district': 'Dinajpur District'},
    'Chitalmari': {'bn': 'চিতলমারী', 'district': 'Bagerhat District'},
    'Chunarughat': {'bn': 'চুনারুঘাট', 'district': 'Habiganj District'},
    'Companiganj': {'bn': 'কোম্পানীগঞ্জ', 'district': 'Noakhali District'},
    'Companiganj Sylhet': {'bn': 'কোম্পানীগঞ্জ', 'district': 'Sylhet District'},
    "Cox's Bazar Sadar": {'bn': 'কক্সবাজার সদর', 'district': "Cox's Bazar District"},
    'Daganbhuiyan': {'bn': 'দাগনভূইয়া', 'district': 'Feni District'},
    'Dakop': {'bn': 'দাকোপ', 'district': 'Khulna District'},
    'Damudya': {'bn': 'ডামুড্যা', 'district': 'Shariatpur District'},
    'Damurhuda': {'bn': 'দামুড়হুদা', 'district': 'Chuadanga District'},
    'Dashmina': {'bn': 'দশমিনা', 'district': 'Patuakhali District'},
    'Daudkandi': {'bn': 'দাউদকান্দি', 'district': 'Comilla District'},
    'Daulatkhan': {'bn': 'দৌলতখান', 'district': 'Bhola District'},
    'Daulatpur': {'bn': 'দৌলতপুর', 'district': 'Kushtia District'},
    'Daulatpur Manikganj': {'bn': 'দৌলতপুর', 'district': 'Manikganj District'},
    'Debhata': {'bn': 'দেবহাটা', 'district': 'Satkhira District'},
    'Debidwar': {'bn': 'দেবিদ্বার', 'district': 'Comilla District'},
    'Debiganj': {'bn': 'দেবীগঞ্জ', 'district': 'Panchagarh District'},
    'Delduar': {'bn': 'দেলদুয়ার', 'district': 'Tangail District'},
    'Dewanganj': {'bn': 'দেওয়ানগঞ্জ', 'district': 'Jamalpur District'},
    'Dhamairhat': {'bn': 'ধামইরহাট', 'district': 'Naogaon District'},
    'Dhamrai': {'bn': 'ধামরাই', 'district': 'Dhaka District'},
    'Dhanbari': {'bn': 'ধানবাড়ী', 'district': 'Tangail District'},
    'Dharmapasha': {'bn': 'ধর্মপাশা', 'district': 'Sunamganj District'},
    'Dhobaura': {'bn': 'ধোবাউড়া', 'district': 'Mymensingh District'},
    'Dhunat': {'bn': 'ধুনট', 'district': 'Bogra District'},
    'Dighinala': {'bn': 'দিঘিনালা', 'district': 'Khagrachhari District'},
    'Dighlia': {'bn': 'দিঘলিয়া', 'district': 'Khulna District'},
    'Dimla': {'bn': 'ডিমলা', 'district': 'Nilphamari District'},
    'Dinajpur Sadar': {'bn': 'দিনাজপুর সদর', 'district': 'Dinajpur District'},
    'Dirai': {'bn': 'দিরাই', 'district': 'Sunamganj District'},
    'Doarabazar': {'bn': 'দোয়ারাবাজার', 'district': 'Sunamganj District'},
    'Dohar': {'bn': 'দোহার', 'district': 'Dhaka District'},
    'Domar': {'bn': 'ডোমার', 'district': 'Nilphamari District'},
    'Dumki': {'bn': 'ডুমকি', 'district': 'Patuakhali District'},
    'Dumuria': {'bn': 'ডুমুরিয়া', 'district': 'Khulna District'},
    'Dupchachiya': {'bn': 'দুপচাঁচিয়া', 'district': 'Bogra District'},
    'Durgapur': {'bn': 'দুর্গাপুর', 'district': 'Netrakona District'},
    'Durgapur Rajshahi': {'bn': 'দুর্গাপুর', 'district': 'Rajshahi District'},
    'Eidgaon': {'bn': 'ঈদগাঁও', 'district': "Cox's Bazar District"},
    'Fakirhat': {'bn': 'ফকিরহাট', 'district': 'Bagerhat District'},
    'Faridganj': {'bn': 'ফরিদগঞ্জ', 'district': 'Chandpur District'},
    'Faridpur': {'bn': 'ফরিদপুর', 'district': 'Pabna District'},
    'Faridpur Sadar': {'bn': 'ফরিদপুর সদর', 'district': 'Faridpur District'},
    'Fatikchhari': {'bn': 'ফটিকছড়ি', 'district': 'Chittagong District'},
    'Fenchuganj': {'bn': 'ফেঞ্চুগঞ্জ', 'district': 'Sylhet District'},
    'Feni Sadar': {'bn': 'ফেনী সদর', 'district': 'Feni District'},
    'Fulbaria': {'bn': 'ফুলবাড়িয়া', 'district': 'Mymensingh District'},
    'Fulchhari': {'bn': 'ফুলছড়ি', 'district': 'Gaibandha District'},
    'Fulgazi': {'bn': 'ফুলগাজী', 'district': 'Feni District'},
    'Fultala': {'bn': 'ফুলতলা', 'district': 'Khulna District'},
    'Gabtoli': {'bn': 'গাবতলী', 'district': 'Bogra District'},
    'Gafargaon': {'bn': 'গফরগাঁও', 'district': 'Mymensingh District'},
    'Gaibandha Sadar': {'bn': 'গাইবান্ধা সদর', 'district': 'Gaibandha District'},
    'Galachipa': {'bn': 'গলাচিপা', 'district': 'Patuakhali District'},
    'Gangachara': {'bn': 'গংগাচড়া', 'district': 'Rangpur District'},
    'Gangni': {'bn': 'গাংনী', 'district': 'Meherpur District'},
    'Gazaria': {'bn': 'গজারিয়া', 'district': 'Munshiganj District'},
    'Gazipur Sadar': {'bn': 'গাজীপুর সদর', 'district': 'Gazipur District'},
    'Ghatail': {'bn': 'ঘাটাইল', 'district': 'Tangail District'},
    'Ghior': {'bn': 'ঘিওর', 'district': 'Manikganj District'},
    'Ghoraghat': {'bn': 'ঘোরাঘাট', 'district': 'Dinajpur District'},
    'Goalanda': {'bn': 'গোয়ালন্দ', 'district': 'Rajbari District'},
    'Gobindaganj': {'bn': 'গোবিন্দগঞ্জ', 'district': 'Gaibandha District'},
    'Godagari': {'bn': 'গোদাগাড়ী', 'district': 'Rajshahi District'},
    'Golapganj': {'bn': 'গোলাপগঞ্জ', 'district': 'Sylhet District'},
    'Gomastapur': {'bn': 'গোমস্তাপুর', 'district': 'Chapainawabganj District'},
    'Gopalganj Sadar': {'bn': 'গোপালগঞ্জ সদর', 'district': 'Gopalganj District'},
    'Gopalpur': {'bn': 'গোপালপুর', 'district': 'Tangail District'},
    'Gosairhat': {'bn': 'গোসাইরহাট', 'district': 'Shariatpur District'},
    'Gouripur': {'bn': 'গৌরীপুর', 'district': 'Mymensingh District'},
    'Gouranadi': {'bn': 'গৌরনদী', 'district': 'Barisal District'},
    'Gowainghat': {'bn': 'গোয়াইনঘাট', 'district': 'Sylhet District'},
    'Guimara': {'bn': 'গুইমারা', 'district': 'Khagrachhari District'},
    'Gurdaspur': {'bn': 'গুরুদাসপুর', 'district': 'Natore District'},
    'Habiganj Sadar': {'bn': 'হবিগঞ্জ সদর', 'district': 'Habiganj District'},
    'Haimchar': {'bn': 'হাইমচর', 'district': 'Chandpur District'},
    'Hajiganj': {'bn': 'হাজীগঞ্জ', 'district': 'Chandpur District'},
    'Hakimpur': {'bn': 'হাকিমপুর', 'district': 'Dinajpur District'},
    'Haluaghat': {'bn': 'হালুয়াঘাট', 'district': 'Mymensingh District'},
    'Harinakundu': {'bn': 'হরিণাকুন্ডু', 'district': 'Jhenaidah District'},
    'Harirampur': {'bn': 'হরিরামপুর', 'district': 'Manikganj District'},
    'Haripur': {'bn': 'হরিপুর', 'district': 'Thakurgaon District'},
    'Hathazari': {'bn': 'হাটহাজারী', 'district': 'Chittagong District'},
    'Hatia': {'bn': 'হাতিয়া', 'district': 'Noakhali District'},
    'Hatibandha': {'bn': 'হাতীবান্ধা', 'district': 'Lalmonirhat District'},
    'Hijla': {'bn': 'হিজলা', 'district': 'Barisal District'},
    'Homna': {'bn': 'হোমনা', 'district': 'Comilla District'},
    'Hossainpur': {'bn': 'হোসেনপুর', 'district': 'Kishoreganj District'},
    'Ishwardi': {'bn': 'ঈশ্বরদী', 'district': 'Pabna District'},
    'Ishwarganj': {'bn': 'ঈশ্বরগঞ্জ', 'district': 'Mymensingh District'},
    'Islampur': {'bn': 'ইসলামপুর', 'district': 'Jamalpur District'},
    'Itna': {'bn': 'ইটনা', 'district': 'Kishoreganj District'},
    'Jagannathpur': {'bn': 'জগন্নাথপুর', 'district': 'Sunamganj District'},
    'Jaintapur': {'bn': 'জৈন্তাপুর', 'district': 'Sylhet District'},
    'Jajira': {'bn': 'জাজিরা', 'district': 'Shariatpur District'},
    'Jaldhaka': {'bn': 'জলঢাকা', 'district': 'Nilphamari District'},
    'Jamalganj': {'bn': 'জামালগঞ্জ', 'district': 'Sunamganj District'},
    'Jamalpur Sadar': {'bn': 'জামালপুর সদর', 'district': 'Jamalpur District'},
    'Jhenaigati': {'bn': 'ঝিনাইগাতী', 'district': 'Sherpur District'},
    'Jhenaidah Sadar': {'bn': 'ঝিনাইদহ সদর', 'district': 'Jhenaidah District'},
    'Jhikargachha': {'bn': 'ঝিকরগাছা', 'district': 'Jessore District'},
    'Jhalokati Sadar': {'bn': 'ঝালকাঠি সদর', 'district': 'Jhalokati District'},
    'Jibannagar': {'bn': 'জীবননগর', 'district': 'Chuadanga District'},
    'Jiyanagar': {'bn': 'জিয়ানগর', 'district': 'Pirojpur District'},
    'Joypurhat Sadar': {'bn': 'জয়পুরহাট সদর', 'district': 'Joypurhat District'},
    'Jurachari': {'bn': 'জুরাছড়ি', 'district': 'Rangamati Hill District'},
    'Juri': {'bn': 'জুড়ী', 'district': 'Moulvibazar District'},
    'Kabirhat': {'bn': 'কবিরহাট', 'district': 'Noakhali District'},
    'Kachua': {'bn': 'কচুয়া', 'district': 'Bagerhat District'},
    'Kachua Chandpur': {'bn': 'কচুয়া', 'district': 'Chandpur District'},
    'Kahalu': {'bn': 'কাহালু', 'district': 'Bogra District'},
    'Kaharol': {'bn': 'কাহারোল', 'district': 'Dinajpur District'},
    'Kalai': {'bn': 'কালাই', 'district': 'Joypurhat District'},
    'Kalaroa': {'bn': 'কালারোয়া', 'district': 'Satkhira District'},
    'Kaliakair': {'bn': 'কালিয়াকৈর', 'district': 'Gazipur District'},
    'Kaliganj': {'bn': 'কালীগঞ্জ', 'district': 'Gazipur District'},
    'Kaliganj Jhenaidah': {'bn': 'কালীগঞ্জ', 'district': 'Jhenaidah District'},
    'Kaliganj Lalmonirhat': {'bn': 'কালীগঞ্জ', 'district': 'Lalmonirhat District'},
    'Kaliganj Satkhira': {'bn': 'কালীগঞ্জ', 'district': 'Satkhira District'},
    'Kalihati': {'bn': 'কালিহাতী', 'district': 'Tangail District'},
    'Kalia': {'bn': 'কালিয়া', 'district': 'Narail District'},
    'Kalkini': {'bn': 'কালকিনি', 'district': 'Madaripur District'},
    'Kalmakanda': {'bn': 'কলমাকান্দা', 'district': 'Netrakona District'},
    'Kalukhali': {'bn': 'কালুখালী', 'district': 'Rajbari District'},
    'Kamalganj': {'bn': 'কামালগঞ্জ', 'district': 'Moulvibazar District'},
    'Kamalnagar': {'bn': 'কমলনগর', 'district': 'Lakshmipur District'},
    'Kamarkhand': {'bn': 'কামারখন্দ', 'district': 'Sirajganj District'},
    'Kanaighat': {'bn': 'কানাইঘাট', 'district': 'Sylhet District'},
    'Kapasia': {'bn': 'কাপাসিয়া', 'district': 'Gazipur District'},
    'Kaptai': {'bn': 'কাপ্তাই', 'district': 'Rangamati Hill District'},
    'Karimganj': {'bn': 'করিমগঞ্জ', 'district': 'Kishoreganj District'},
    'Karnaphuli': {'bn': 'কর্ণফুলী', 'district': 'Chittagong District'},
    'Kasba': {'bn': 'কসবা', 'district': 'Brahmanbaria District'},
    'Kashiani': {'bn': 'কাশিয়ানী', 'district': 'Gopalganj District'},
    'Kathalia': {'bn': 'কাঠালিয়া', 'district': 'Jhalokati District'},
    'Katiadi': {'bn': 'কটিয়াদী', 'district': 'Kishoreganj District'},
    'Kaukhali': {'bn': 'কাউখালী', 'district': 'Pirojpur District'},
    'Kaukhali Rangamati': {'bn': 'কাউখালী', 'district': 'Rangamati Hill District'},
    'Kaunia': {'bn': 'কাউনিয়া', 'district': 'Rangpur District'},
    'Kazipur': {'bn': 'কাজীপুর', 'district': 'Sirajganj District'},
    'Kendua': {'bn': 'কেন্দুয়া', 'district': 'Netrakona District'},
    'Keraniganj': {'bn': 'কেরানীগঞ্জ', 'district': 'Dhaka District'},
    'Keshabpur': {'bn': 'কেশবপুর', 'district': 'Jessore District'},
    'Khagrachhari Sadar': {'bn': 'খাগড়াছড়ি সদর', 'district': 'Khagrachhari District'},
    'Khaliajuri': {'bn': 'খালিয়াজুরী', 'district': 'Netrakona District'},
    'Khansama': {'bn': 'খানসামা', 'district': 'Dinajpur District'},
    'Khetlal': {'bn': 'ক্ষেতলাল', 'district': 'Joypurhat District'},
    'Khoksa': {'bn': 'খোকসা', 'district': 'Kushtia District'},
    'Kishoreganj': {'bn': 'কিশোরগঞ্জ', 'district': 'Nilphamari District'},
    'Kishoreganj Sadar': {'bn': 'কিশোরগঞ্জ সদর', 'district': 'Kishoreganj District'},
    'Kotalipara': {'bn': 'কোটালীপাড়া', 'district': 'Gopalganj District'},
    'Kotchandpur': {'bn': 'কোটচাঁদপুর', 'district': 'Jhenaidah District'},
    'Koyra': {'bn': 'কয়রা', 'district': 'Khulna District'},
    'Kuliarchar': {'bn': 'কুলিয়ারচর', 'district': 'Kishoreganj District'},
    'Kulaura': {'bn': 'কুলাউড়া', 'district': 'Moulvibazar District'},
    'Kumarkhali': {'bn': 'কুমারখালী', 'district': 'Kushtia District'},
    'Kurigram Sadar': {'bn': 'কুড়িগ্রাম সদর', 'district': 'Kurigram District'},
    'Kushtia Sadar': {'bn': 'কুষ্টিয়া সদর', 'district': 'Kushtia District'},
    'Kutubdia': {'bn': 'কুতুবদিয়া', 'district': "Cox's Bazar District"},
    'Lakhai': {'bn': 'লাখাই', 'district': 'Habiganj District'},
    'Laksam': {'bn': 'লাকসাম', 'district': 'Comilla District'},
    'Lakshmichari': {'bn': 'লক্ষ্মীছড়ি', 'district': 'Khagrachhari District'},
    'Lakshmipur Sadar': {'bn': 'লক্ষ্মীপুর সদর', 'district': 'Lakshmipur District'},
    'Lalpur': {'bn': 'লালপুর', 'district': 'Natore District'},
    'Lalmonirhat Sadar': {'bn': 'লালমনিরহাট সদর', 'district': 'Lalmonirhat District'},
    'Lama': {'bn': 'লামা', 'district': 'Bandarban District'},
    'Langadu': {'bn': 'লংগদু', 'district': 'Rangamati Hill District'},
    'Lauhajang': {'bn': 'লৌহজং', 'district': 'Munshiganj District'},
    'Lohagara': {'bn': 'লোহাগাড়া', 'district': 'Chittagong District'},
    'Lohagara Narail': {'bn': 'লোহাগড়া', 'district': 'Narail District'},
    'Madaripur Sadar': {'bn': 'মাদারীপুর সদর', 'district': 'Madaripur District'},
    'Madhabpur': {'bn': 'মাধবপুর', 'district': 'Habiganj District'},
    'Madan': {'bn': 'মদন', 'district': 'Netrakona District'},
    'Madarganj': {'bn': 'মাদারগঞ্জ', 'district': 'Jamalpur District'},
    'Madhukhali': {'bn': 'মধুখালী', 'district': 'Faridpur District'},
    'Madhupur': {'bn': 'মধুপুর', 'district': 'Tangail District'},
    'Magura Sadar': {'bn': 'মাগুরা সদর', 'district': 'Magura District'},
    'Mahadevpur': {'bn': 'মহাদেবপুর', 'district': 'Naogaon District'},
    'Mahalchhari': {'bn': 'মহালছড়ি', 'district': 'Khagrachhari District'},
    'Maheshkhali': {'bn': 'মহেশখালী', 'district': "Cox's Bazar District"},
    'Maheshpur': {'bn': 'মহেশপুর', 'district': 'Jhenaidah District'},
    'Manda': {'bn': 'মান্দা', 'district': 'Naogaon District'},
    'Manikchhari': {'bn': 'মানিকছড়ি', 'district': 'Khagrachhari District'},
    'Manikganj Sadar': {'bn': 'মানিকগঞ্জ সদর', 'district': 'Manikganj District'},
    'Manirampur': {'bn': 'মণিরামপুর', 'district': 'Jessore District'},
    'Manoharganj': {'bn': 'মনোহরগঞ্জ', 'district': 'Comilla District'},
    'Manohardi': {'bn': 'মনোহরদী', 'district': 'Narsingdi District'},
    'Mathbaria': {'bn': 'মঠবাড়িয়া', 'district': 'Pirojpur District'},
    'Matiranga': {'bn': 'মাটিরাঙ্গা', 'district': 'Khagrachhari District'},
    'Matlab South': {'bn': 'মাতলাব দক্ষিণ', 'district': 'Chandpur District'},
    'Meghna': {'bn': 'মেঘনা', 'district': 'Comilla District'},
    'Mehendiganj': {'bn': 'মেহেন্দিগঞ্জ', 'district': 'Barisal District'},
    'Meherpur Sadar': {'bn': 'মেহেরপুর সদর', 'district': 'Meherpur District'},
    'Melandaha': {'bn': 'মেলান্দহ', 'district': 'Jamalpur District'},
    'Mirpur': {'bn': 'মিরপুর', 'district': 'Kushtia District'},
    'Mirsarai': {'bn': 'মীরসরাই', 'district': 'Chittagong District'},
    'Mirzaganj': {'bn': 'মির্জাগঞ্জ', 'district': 'Patuakhali District'},
    'Mirzapur': {'bn': 'মির্জাপুর', 'district': 'Tangail District'},
    'Mithamain': {'bn': 'মিঠামইন', 'district': 'Kishoreganj District'},
    'Mithapukur': {'bn': 'মিঠাপুকুর', 'district': 'Rangpur District'},
    'Mohanganj': {'bn': 'মোহনগঞ্জ', 'district': 'Netrakona District'},
    'Mohammadpur': {'bn': 'মোহাম্মদপুর', 'district': 'Magura District'},
    'Mohanpur': {'bn': 'মোহনপুর', 'district': 'Rajshahi District'},
    'Mollahat': {'bn': 'মোড়েলগঞ্জ', 'district': 'Bagerhat District'},
    'Mongla': {'bn': 'মোংলা', 'district': 'Bagerhat District'},
    'Monohardi': {'bn': 'মনোহরদী', 'district': 'Narsingdi District'},
    'Monpura': {'bn': 'মনপুরা', 'district': 'Bhola District'},
    'Morelganj': {'bn': 'মোরেলগঞ্জ', 'district': 'Bagerhat District'},
    'Moulvibazar Sadar': {'bn': 'মৌলভীবাজার সদর', 'district': 'Moulvibazar District'},
    'Mujibnagar': {'bn': 'মুজিবনগর', 'district': 'Meherpur District'},
    'Muktagachha': {'bn': 'মুক্তাগাছা', 'district': 'Mymensingh District'},
    'Muksudpur': {'bn': 'মুকসুদপুর', 'district': 'Gopalganj District'},
    'Muladi': {'bn': 'মুলাদী', 'district': 'Barisal District'},
    'Munshiganj Sadar': {'bn': 'মুন্সিগঞ্জ সদর', 'district': 'Munshiganj District'},
    'Muradnagar': {'bn': 'মুরাদনগর', 'district': 'Comilla District'},
    'Mymensingh Sadar': {'bn': 'ময়মনসিংহ সদর', 'district': 'Mymensingh District'},
    'Nabinagar': {'bn': 'নবীগঞ্জ', 'district': 'Brahmanbaria District'},
    'Nabiganj': {'bn': 'নবীগঞ্জ', 'district': 'Habiganj District'},
    'Nachol': {'bn': 'নাচোল', 'district': 'Chapainawabganj District'},
    'Nagarkanda': {'bn': 'নগরকান্দা', 'district': 'Faridpur District'},
    'Nagarpur': {'bn': 'নাগরপুর', 'district': 'Tangail District'},
    'Nageshwari': {'bn': 'নাগেশ্বরী', 'district': 'Kurigram District'},
    'Naikyangchhari': {'bn': 'নাইক্ষ্যংছড়ি', 'district': 'Bandarban District'},
    'Nakla': {'bn': 'নকলা', 'district': 'Sherpur District'},
    'Nalchiti': {'bn': 'নলছিটি', 'district': 'Jhalokati District'},
    'Naldanga': {'bn': 'নলডাঙ্গা', 'district': 'Natore District'},
    'Nalitabari': {'bn': 'নালিতাবাড়ী', 'district': 'Sherpur District'},
    'Nandail': {'bn': 'নান্দাইল', 'district': 'Mymensingh District'},
    'Nandigram': {'bn': 'নন্দীগ্রাম', 'district': 'Bogra District'},
    'Nangalkot': {'bn': 'নাঙ্গলকোট', 'district': 'Comilla District'},
    'Naniarchar': {'bn': 'নানিয়ারচর', 'district': 'Rangamati Hill District'},
    'Naogaon Sadar': {'bn': 'নওগাঁ সদর', 'district': 'Naogaon District'},
    'Narail Sadar': {'bn': 'নড়াইল সদর', 'district': 'Narail District'},
    'Narayanganj Sadar': {'bn': 'নারায়ণগঞ্জ সদর', 'district': 'Narayanganj District'},
    'Naria': {'bn': 'নড়িয়া', 'district': 'Shariatpur District'},
    'Narsingdi Sadar': {'bn': 'নরসিংদী সদর', 'district': 'Narsingdi District'},
    'Nasirnagar': {'bn': 'নাসিরনগর', 'district': 'Brahmanbaria District'},
    'Natore Sadar': {'bn': 'নাটোর সদর', 'district': 'Natore District'},
    'Nawabganj': {'bn': 'নবাবগঞ্জ', 'district': 'Dhaka District'},
    'Nawabganj Dinajpur': {'bn': 'নবাবগঞ্জ', 'district': 'Dinajpur District'},
    'Nazirpur': {'bn': 'নাজিরপুর', 'district': 'Pirojpur District'},
    'Nesarabad': {'bn': 'নেছারাবাদ', 'district': 'Pirojpur District'},
    'Netrakona Sadar': {'bn': 'নেত্রকোনা সদর', 'district': 'Netrakona District'},
    'Niamatpur': {'bn': 'নিয়ামতপুর', 'district': 'Naogaon District'},
    'Nikli': {'bn': 'নিকলী', 'district': 'Kishoreganj District'},
    'Nilphamari Sadar': {'bn': 'নীলফামারী সদর', 'district': 'Nilphamari District'},
    'Noakhali Sadar': {'bn': 'নোয়াখালী সদর', 'district': 'Noakhali District'},
    'Osmani Nagar': {'bn': 'ওসমানী নগর', 'district': 'Sylhet District'},
    'Paba': {'bn': 'পবা', 'district': 'Rajshahi District'},
    'Pabna Sadar': {'bn': 'পাবনা সদর', 'district': 'Pabna District'},
    'Paikgachha': {'bn': 'পাইকগাছা', 'district': 'Khulna District'},
    'Pakundia': {'bn': 'পাকুন্দিয়া', 'district': 'Kishoreganj District'},
    'Palash': {'bn': 'পলাশ', 'district': 'Narsingdi District'},
    'Palashbari': {'bn': 'পলাশবাড়ী', 'district': 'Gaibandha District'},
    'Panchagarh Sadar': {'bn': 'পঞ্চগড় সদর', 'district': 'Panchagarh District'},
    'Panchbibi': {'bn': 'পঞ্চবিবি', 'district': 'Joypurhat District'},
    'Panchhari': {'bn': 'পানছড়ি', 'district': 'Khagrachhari District'},
    'Pangsha': {'bn': 'পাংশা', 'district': 'Rajbari District'},
    'Parashuram': {'bn': 'পরশুরাম', 'district': 'Feni District'},
    'Parbatipur': {'bn': 'পার্বতীপুর', 'district': 'Dinajpur District'},
    'Patharghata': {'bn': 'পাথরঘাটা', 'district': 'Barguna District'},
    'Patiya': {'bn': 'পটিয়া', 'district': 'Chittagong District'},
    'Patgram': {'bn': 'পাটগ্রাম', 'district': 'Lalmonirhat District'},
    'Patnitala': {'bn': 'পত্নীতলা', 'district': 'Naogaon District'},
    'Patuakhali Sadar': {'bn': 'পটুয়াখালী সদর', 'district': 'Patuakhali District'},
    'Pekua': {'bn': 'পেকুয়া', 'district': "Cox's Bazar District"},
    'Phulbari': {'bn': 'ফুলবাড়ী', 'district': 'Dinajpur District'},
    'Phulbari Kurigram': {'bn': 'ফুলবাড়ী', 'district': 'Kurigram District'},
    'Phulpur': {'bn': 'ফুলপুর', 'district': 'Mymensingh District'},
    'Pirgachha': {'bn': 'পীরগাছা', 'district': 'Rangpur District'},
    'Pirganj': {'bn': 'পীরগঞ্জ', 'district': 'Rangpur District'},
    'Pirganj Thakurgaon': {'bn': 'পীরগঞ্জ', 'district': 'Thakurgaon District'},
    'Pirojpur Sadar': {'bn': 'পিরোজপুর সদর', 'district': 'Pirojpur District'},
    'Porsha': {'bn': 'পোরশা', 'district': 'Naogaon District'},
    'Purbadhala': {'bn': 'পূর্বধলা', 'district': 'Netrakona District'},
    'Puthia': {'bn': 'পুঠিয়া', 'district': 'Rajshahi District'},
    'Raiganj': {'bn': 'রায়গঞ্জ', 'district': 'Sirajganj District'},
    'Raipura': {'bn': 'রায়পুরা', 'district': 'Narsingdi District'},
    'Raipur': {'bn': 'রায়পুর', 'district': 'Lakshmipur District'},
    'Rajarhat': {'bn': 'রাজারহাট', 'district': 'Kurigram District'},
    'Rajapur': {'bn': 'রাজাপুর', 'district': 'Jhalokati District'},
    'Rajbari Sadar': {'bn': 'রাজবাড়ী সদর', 'district': 'Rajbari District'},
    'Rajnagar': {'bn': 'রাজনগর', 'district': 'Moulvibazar District'},
    'Rajoir': {'bn': 'রাজৈর', 'district': 'Madaripur District'},
    'Rajasthali': {'bn': 'রাজস্থলী', 'district': 'Rangamati Hill District'},
    'Rajshahi Sadar': {'bn': 'রাজশাহী সদর', 'district': 'Rajshahi District'},
    'Ramganj': {'bn': 'রামগঞ্জ', 'district': 'Lakshmipur District'},
    'Ramgarh': {'bn': 'রামগড়', 'district': 'Khagrachhari District'},
    'Ramgati': {'bn': 'রামগতি', 'district': 'Lakshmipur District'},
    'Rampal': {'bn': 'রামপাল', 'district': 'Bagerhat District'},
    'Ramu': {'bn': 'রামু', 'district': "Cox's Bazar District"},
    'Rangabali': {'bn': 'রাঙ্গাবালী', 'district': 'Patuakhali District'},
    'Rangamati Sadar': {'bn': 'রাঙ্গামাটি সদর', 'district': 'Rangamati Hill District'},
    'Rangunia': {'bn': 'রাঙ্গুনিয়া', 'district': 'Chittagong District'},
    'Rangpur Sadar': {'bn': 'রংপুর সদর', 'district': 'Rangpur District'},
    'Raninagar': {'bn': 'রাণীনগর', 'district': 'Naogaon District'},
    'Ranishankail': {'bn': 'রাণীশংকৈল', 'district': 'Thakurgaon District'},
    'Raozan': {'bn': 'রাউজান', 'district': 'Chittagong District'},
    'Roumari': {'bn': 'রৌমারী', 'district': 'Kurigram District'},
    'Rowangchhari': {'bn': 'রোয়াংছড়ি', 'district': 'Bandarban District'},
    'Ruma': {'bn': 'রুমা', 'district': 'Bandarban District'},
    'Rupganj': {'bn': 'রূপগঞ্জ', 'district': 'Narayanganj District'},
    'Rupsa': {'bn': 'রূপসা', 'district': 'Khulna District'},
    'Sadarpur': {'bn': 'সদরপুর', 'district': 'Faridpur District'},
    'Sadar South': {'bn': 'সদর দক্ষিণ', 'district': 'Comilla District'},
    'Sadullapur': {'bn': 'সাদুল্লাপুর', 'district': 'Gaibandha District'},
    'Saghata': {'bn': 'সাঘাটা', 'district': 'Gaibandha District'},
    'Saidpur': {'bn': 'সৈয়দপুর', 'district': 'Nilphamari District'},
    'Sakhipur': {'bn': 'সখিপুর', 'district': 'Tangail District'},
    'Saltha': {'bn': 'সালথা', 'district': 'Faridpur District'},
    'Sandwip': {'bn': 'সন্দ্বীপ', 'district': 'Chittagong District'},
    'Santhia': {'bn': 'সাঁথিয়া', 'district': 'Pabna District'},
    'Sapahar': {'bn': 'সাপাহার', 'district': 'Naogaon District'},
    'Sarail': {'bn': 'সরাইল', 'district': 'Brahmanbaria District'},
    'Sariakandi': {'bn': 'সারিয়াকান্দি', 'district': 'Bogra District'},
    'Sarishabari': {'bn': 'সরিষাবাড়ী', 'district': 'Jamalpur District'},
    'Satkania': {'bn': 'সাতকানিয়া', 'district': 'Chittagong District'},
    'Satkhira Sadar': {'bn': 'সাতক্ষীরা সদর', 'district': 'Satkhira District'},
    'Saturia': {'bn': 'সাটুরিয়া', 'district': 'Manikganj District'},
    'Savar': {'bn': 'সাভার', 'district': 'Dhaka District'},
    'Senbag': {'bn': 'সেনবাগ', 'district': 'Noakhali District'},
    'Shahjadpur': {'bn': 'শাহজাদপুর', 'district': 'Sirajganj District'},
    'Shahrasti': {'bn': 'শাহরাস্তি', 'district': 'Chandpur District'},
    'Shailkupa': {'bn': 'শৈলকুপা', 'district': 'Jhenaidah District'},
    'Shajahanpur': {'bn': 'শাজাহানপুর', 'district': 'Bogra District'},
    'Shalikha': {'bn': 'শালিখা', 'district': 'Magura District'},
    'Shalla': {'bn': 'শাল্লা', 'district': 'Sunamganj District'},
    'Sharankhola': {'bn': 'শরণখোলা', 'district': 'Bagerhat District'},
    'Shariatpur Sadar': {'bn': 'শরীয়তপুর সদর', 'district': 'Shariatpur District'},
    'Sharsha': {'bn': 'শার্শা', 'district': 'Jessore District'},
    'Shayestaganj': {'bn': 'শায়েস্তাগঞ্জ', 'district': 'Habiganj District'},
    'Sherpur': {'bn': 'শেরপুর', 'district': 'Bogra District'},
    'Sherpur Sadar': {'bn': 'শেরপুর সদর', 'district': 'Sherpur District'},
    'Shibchar': {'bn': 'শিবচর', 'district': 'Madaripur District'},
    'Shibganj': {'bn': 'শিবগঞ্জ', 'district': 'Bogra District'},
    'Shibganj Chapai': {'bn': 'শিবগঞ্জ', 'district': 'Chapainawabganj District'},
    'Shibpur': {'bn': 'শিবপুর', 'district': 'Narsingdi District'},
    'Shivaloy': {'bn': 'শিবালয়', 'district': 'Manikganj District'},
    'Singair': {'bn': 'সিঙ্গাইর', 'district': 'Manikganj District'},
    'Singra': {'bn': 'সিংড়া', 'district': 'Natore District'},
    'Sirajdikhan': {'bn': 'সিরাজদিখান', 'district': 'Munshiganj District'},
    'Sirajganj Sadar': {'bn': 'সিরাজগঞ্জ সদর', 'district': 'Sirajganj District'},
    'Sitakunda': {'bn': 'সীতাকুণ্ড', 'district': 'Chittagong District'},
    'Sonaimuri': {'bn': 'সোনাইমুড়ী', 'district': 'Noakhali District'},
    'Sonargaon': {'bn': 'সোনারগাঁও', 'district': 'Narayanganj District'},
    'Sonagazi': {'bn': 'সোনাগাজী', 'district': 'Feni District'},
    'Sonatala': {'bn': 'সোনাতলা', 'district': 'Bogra District'},
    'South Surma': {'bn': 'দক্ষিণ সুরমা', 'district': 'Sylhet District'},
    'Sreepur': {'bn': 'শ্রীপুর', 'district': 'Gazipur District'},
    'Sreepur Magura': {'bn': 'শ্রীপুর', 'district': 'Magura District'},
    'Sribardi': {'bn': 'শ্রীবরদী', 'district': 'Sherpur District'},
    'Srimangal': {'bn': 'শ্রীমঙ্গল', 'district': 'Moulvibazar District'},
    'Srinagar': {'bn': 'শ্রীনগর', 'district': 'Munshiganj District'},
    'Subarnachar': {'bn': 'সুবর্ণচর', 'district': 'Noakhali District'},
    'Sujanagar': {'bn': 'সুজানগর', 'district': 'Pabna District'},
    'Sunamganj Sadar': {'bn': 'সুনামগঞ্জ সদর', 'district': 'Sunamganj District'},
    'Sundarganj': {'bn': 'সুন্দরগঞ্জ', 'district': 'Gaibandha District'},
    'Sylhet Sadar': {'bn': 'সিলেট সদর', 'district': 'Sylhet District'},
    'Tahirpur': {'bn': 'তাহিরপুর', 'district': 'Sunamganj District'},
    'Tajumuddin': {'bn': 'তাজুমুদ্দিন', 'district': 'Bhola District'},
    'Taltoli': {'bn': 'তালতলী', 'district': 'Barguna District'},
    'Tangail Sadar': {'bn': 'টাঙ্গাইল সদর', 'district': 'Tangail District'},
    'Tanor': {'bn': 'তানোর', 'district': 'Rajshahi District'},
    'Taraganj': {'bn': 'তারাগঞ্জ', 'district': 'Rangpur District'},
    'Tarail': {'bn': 'তাড়াইল', 'district': 'Kishoreganj District'},
    'Tarakanda': {'bn': 'তারাকান্দা', 'district': 'Mymensingh District'},
    'Tarash': {'bn': 'তাড়াশ', 'district': 'Sirajganj District'},
    'Teknaf': {'bn': 'টেকনাফ', 'district': "Cox's Bazar District"},
    'Tentulia': {'bn': 'তেঁতুলিয়া', 'district': 'Panchagarh District'},
    'Terkhada': {'bn': 'তেরখাদা', 'district': 'Khulna District'},
    'Thakurgaon Sadar': {'bn': 'ঠাকুরগাঁও সদর', 'district': 'Thakurgaon District'},
    'Thanchi': {'bn': 'থানচি', 'district': 'Bandarban District'},
    'Titas': {'bn': 'তিতাস', 'district': 'Comilla District'},
    'Tongibari': {'bn': 'টঙ্গিবাড়ী', 'district': 'Munshiganj District'},
    'Trishal': {'bn': 'ত্রিশাল', 'district': 'Mymensingh District'},
    'Tungipara': {'bn': 'টুঙ্গিপাড়া', 'district': 'Gopalganj District'},
    'Ujirpur': {'bn': 'উজিরপুর', 'district': 'Barisal District'},
    'Ukhia': {'bn': 'উখিয়া', 'district': "Cox's Bazar District"},
    'Ulipur': {'bn': 'উলিপুর', 'district': 'Kurigram District'},
    'Ullapara': {'bn': 'উল্লাপাড়া', 'district': 'Sirajganj District'},
    'Zakiganj': {'bn': 'জকিগঞ্জ', 'district': 'Sylhet District'},
}

# ─── Duplicate resolution ───
# Some upazila names appear in multiple districts under same or different keys.
# Resolve preferred district suffix.
_UPAZILA_DISTRICT_OVERRIDE = {
    ('Daulatpur', 'Manikganj'): 'Daulatpur Manikganj',
    ('Daulatpur', 'Kushtia'): 'Daulatpur',
    ('Durgapur', 'Netrakona'): 'Durgapur',
    ('Durgapur', 'Rajshahi'): 'Durgapur Rajshahi',
    ('Kachua', 'Bagerhat'): 'Kachua',
    ('Kachua', 'Chandpur'): 'Kachua Chandpur',
    ('Kaliganj', 'Gazipur'): 'Kaliganj',
    ('Kaliganj', 'Jhenaidah'): 'Kaliganj Jhenaidah',
    ('Kaliganj', 'Lalmonirhat'): 'Kaliganj Lalmonirhat',
    ('Kaliganj', 'Satkhira'): 'Kaliganj Satkhira',
    ('Kaukhali', 'Pirojpur'): 'Kaukhali',
    ('Kaukhali', 'Rangamati'): 'Kaukhali Rangamati',
    ('Lohagara', 'Chittagong'): 'Lohagara',
    ('Lohagara', 'Narail'): 'Lohagara Narail',
    ('Nawabganj', 'Dhaka'): 'Nawabganj',
    ('Nawabganj', 'Dinajpur'): 'Nawabganj Dinajpur',
    ('Phulbari', 'Dinajpur'): 'Phulbari',
    ('Phulbari', 'Kurigram'): 'Phulbari Kurigram',
    ('Pirganj', 'Rangpur'): 'Pirganj',
    ('Pirganj', 'Thakurgaon'): 'Pirganj Thakurgaon',
    ('Shibganj', 'Bogra'): 'Shibganj',
    ('Shibganj', 'Chapainawabganj'): 'Shibganj Chapai',
    ('Sreepur', 'Gazipur'): 'Sreepur',
    ('Sreepur', 'Magura'): 'Sreepur Magura',
    ('Kaliganj', 'Satkhira'): 'Kaliganj Satkhira',
    ('Companiganj', 'Noakhali'): 'Companiganj',
    ('Daulatpur', 'Manikganj'): 'Daulatpur Manikganj',
    ('Monohardi', 'Narsingdi'): 'Monohardi',
    ('Chhagalnaiya', 'Feni'): 'Chagalnaiya',
}

_TITLE_EXCEPTIONS = {
    "coxs": "Cox's",
    "Coxs": "Cox's",
}

# Normalize: ensure every upazila has a district reference
_UPAZILA_BY_DISTRICT = {}
for name, info in UPAZILAS.items():
    dist = info['district']
    _UPAZILA_BY_DISTRICT.setdefault(dist, []).append(name)


# ─── Helpers ───

def parse_upazila(raw):
    if not raw:
        return ''
    raw = raw.strip()
    return raw.replace(' Upazila', '').replace(' upazila', '').strip()


def parse_district(raw):
    if not raw:
        return ''
    raw = raw.strip().replace(' District', '').replace(' district', '').strip()
    return f'{raw} District' if raw else ''


def lookup_division(district_key):
    info = DISTRICTS.get(district_key)
    if info:
        return info['division']
    bare = district_key.replace(' District', '').strip()
    div_key = DIVISION_LOOKUP.get(bare)
    if div_key:
        return div_key
    for dk, dv in DISTRICTS.items():
        if dk.startswith(bare):
            return dv['division']
    return ''


def generate_slug(upazila, district):
    from .models import generate_partner_slug
    raw = f'{upazila}-Upazila-{district}' if district else upazila
    return generate_partner_slug(raw)


def generate_description(upazila, district):
    upazila_bn = ''
    district_bn = ''
    up_info = UPAZILAS.get(upazila)
    if up_info:
        upazila_bn = up_info.get('bn', '') or ''
    dist_info = DISTRICTS.get(district)
    if dist_info:
        raw = dist_info.get('bn', '') or ''
        district_bn = raw.replace(' জেলা', '').strip()
    up_name = upazila_bn or upazila
    dist_name = district_bn or district.replace(' District', '').strip()
    return f'{up_name} উপজেলা, {dist_name} জেলা'


def resolve_header(header):
    """Map verbose CSV header to model field name."""
    mapping = {
        'user': 'user',
        'name': 'name',
        'slug': 'slug',
        'logo': 'logo',
        'profile image': 'profile_image',
        'profile_image': 'profile_image',
        'banner': 'banner',
        'description': 'description',
        'phone': 'phone',
        'address': 'address',
        'street / village / house / flat': 'address_street',
        'street': 'address_street',
        'village': 'address_street',
        'division': 'address_division',
        'district': 'address_district',
        'upazila': 'address_upazila',
        'voter id card': 'voter_id',
        'voter_id': 'voter_id',
        'is dealer': 'is_dealer',
        'is_dealer': 'is_dealer',
        'is seller': 'is_seller',
        'is_seller': 'is_seller',
        'is union agent': 'is_union_agent',
        'is_union_agent': 'is_union_agent',
        'is active': 'is_active',
        'is_active': 'is_active',
        'dealer (parent)': 'parent',
        'dealer': 'parent',
        'parent': 'parent',
        'parent_name': 'parent',
        'meta title': 'meta_title',
        'meta_title': 'meta_title',
        'meta description': 'meta_description',
        'meta_description': 'meta_description',
        'show products on website': 'show_products',
        'show_products': 'show_products',
        'show "all over available product" section on store page': 'show_all_products_section',
        'show_all_products_section': 'show_all_products_section',
        'show "random product list" section on store page': 'show_random_products_section',
        'show_random_products_section': 'show_random_products_section',
        'show slider on store page': 'show_slider',
        'show_slider': 'show_slider',
        'shop style': 'shop_style',
        'shop_style': 'shop_style',
        'medicine catalog access': 'has_medicine_access',
        'has_medicine_access': 'has_medicine_access',
        'medicine pos enabled': 'medicine_pos_enabled',
        'medicine_pos_enabled': 'medicine_pos_enabled',
        'created': 'created',
        'updated': 'updated',
    }
    key = header.strip().lower()
    if key in mapping:
        return mapping[key]
    return header.strip()


def parse_bool(val):
    if isinstance(val, bool):
        return val
    if val is None:
        return False
    s = str(val).strip().lower()
    return s in ('1', 'true', 'yes', 'y', 'on', 'dealer', 'seller')


def normalize_shop_style(val):
    if not val:
        return 'general'
    v = str(val).strip().lower()
    if v in ('general', 'shoe', 'medicine'):
        return v
    return 'general'
